include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true 
    avoid_relative_lib_imports: true
    use_key_in_widget_constructors: true
    avoid_escaping_inner_quotes: true
    avoid_multiple_declarations_per_line: true
    avoid_returning_null_for_void: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    constant_identifier_names: false
    curly_braces_in_flow_control_structures: true
    prefer_if_null_operators: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    unnecessary_new: true
    unnecessary_brace_in_string_interps: true
    must_be_immutable: true
